services:
  scpi-validation-db:
    image: mongo:6
    container_name: scpi-validation-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: scpi_validation_db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-validation
    ports:
      - "8086:8081"
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://admin:admin@scpi-validation-db:27017/scpi_validation_db?authSource=admin"
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

