spring:
  application:
    name: scpi-doc-validation-api

  data:
    mongodb:
      uri: mongodb://admin:admin@scpi-doc-validation-db:27017/int.scpi_validation_db?authSource=admin

minio:
  url: "http://minio-service.minio.svc.cluster.local:9000"
  access-key: admin
  secret-key: admin-admin