spring:
  application:
    name: scpi-doc-validation-api

  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/scpi_validation_db?authSource=admin

  kafka:
    bootstrap-servers: kafka-svc.kafka:9094







