apiVersion: apps/v1
kind: Deployment
metadata:
  name: scpi-doc-validation-db
  labels:
    app: scpi-doc-validation-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scpi-doc-validation-db
  template:
    metadata:
      labels:
        app: scpi-doc-validation-db
    spec:
      containers:
        - name: mongo
          image: mongo:6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin
            - name: MONGO_INITDB_DATABASE
              value: scpi_validation_db
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: { { .Release.Name } }-pvc
      restartPolicy: Always
