apiVersion: apps/v1
kind: Deployment
metadata:
  name: scpi-doc-validation-api
  labels:
    app: scpi-doc-validation-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scpi-doc-validation-api
  template:
    metadata:
      name: scpi-doc-validation-api
      labels:
        app: sscpi-doc-validation-api
    spec:
      containers:
        - name: scpi-doc-validation-api
          image: "{{.Values.image.repo}}/{{.Values.image.name}}:{{.Values.image.tag}}"
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value:  "{{.Values.application.environment }}"