apiVersion: v1
kind: Service
metadata:
  name: scpi-doc-validation-api
spec:
  selector:
    app: scpi-doc-validation-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP